"""Advanced curriculum domains added in program version 2."""

EXPANSION_PARTS = [
    {
        "slug": "systems-architecture-engineering",
        "title": "Arquitectura de sistemas e ingeniería de requisitos",
        "level": "intermedio-avanzado",
        "focus": "Pasar de requisitos ambiguos a arquitecturas comprobables antes de elegir servicios cloud.",
        "model": "Una arquitectura es un conjunto de decisiones sobre estructuras, interfaces y atributos de calidad, respaldadas por escenarios y evidencia.",
        "books": ["Software Architecture in Practice — Bass, Clements y Kazman", "Fundamentals of Software Architecture — Richards y Ford", "Designing Data-Intensive Applications — Martin Kleppmann"],
        "classes": [
            ("Requisitos funcionales, restricciones y atributos de calidad", "architecture", "quality-attribute-scenarios"),
            ("Contexto, contenedores, componentes y código con C4", "architecture", "c4-model"),
            ("Acoplamiento, cohesión, modularidad y fronteras", "architecture", "module-map"),
            ("Arquitectura monolítica, modular y de microservicios", "decision", "architecture-style-adr"),
            ("Disponibilidad, confiabilidad y análisis de puntos de fallo", "reliability", "failure-mode-analysis"),
            ("Capacidad, latencia, throughput y teoría de colas", "performance", "capacity-model"),
            ("Consistencia, particiones, relojes y consenso", "distributed", "consistency-model"),
            ("Contratos de API, eventos y compatibilidad evolutiva", "api", "contract-evolution"),
            ("Modelado de amenazas y arquitectura de confianza cero", "security", "system-threat-model"),
            ("ADRs, fitness functions y gobierno de decisiones", "architecture", "adr-library"),
            ("Architecture review y comunicación con stakeholders", "governance", "architecture-review"),
            ("Proyecto: arquitectura completa de CloudShop", "capstone", "cloudshop-system-design"),
        ],
    },
    {
        "slug": "advanced-cloud-networking-edge",
        "title": "Redes cloud avanzadas, conectividad híbrida y edge",
        "level": "avanzado",
        "focus": "Diseñar conectividad segura y observable entre regiones, proveedores, centros de datos y edge.",
        "model": "La red cloud es un sistema distribuido de rutas, identidades y políticas; cada salto añade latencia, costo y una frontera de fallo.",
        "books": ["Computer Networking: A Top-Down Approach — Kurose y Ross", "Cloud Native Data Center Networking — Dinesh Dutt", "AWS Advanced Networking Study Guide — S. Mahalingam"],
        "classes": [
            ("CIDR, subnetting y planificación IP a escala", "network", "ipam-plan"),
            ("Routing, BGP, tránsito y propagación de rutas", "network", "routing-lab"),
            ("DNS autoritativo, recursivo, split-horizon y DNSSEC", "network", "dns-design"),
            ("Balanceo L4/L7, proxies, TLS y gestión de certificados", "network", "traffic-entry"),
            ("CDN, caché, origin shielding y edge compute", "performance", "cdn-experiment"),
            ("VPN, Direct Connect, ExpressRoute e Interconnect", "network", "hybrid-connectivity"),
            ("Transit Gateway, Virtual WAN y Network Connectivity Center", "network", "transit-comparison"),
            ("Private endpoints, service networking y egress control", "security", "private-connectivity"),
            ("Service mesh, mTLS y gestión de tráfico este-oeste", "network", "service-mesh"),
            ("eBPF, flow logs, packet capture y diagnóstico", "observability", "network-evidence"),
            ("SD-WAN, 5G, IoT y operación desconectada", "architecture", "edge-topology"),
            ("Proyecto: red multi-región y multi-cloud", "capstone", "multicloud-network"),
        ],
    },
    {
        "slug": "aws-production-architecture",
        "title": "AWS: arquitectura, automatización y operación en producción",
        "level": "avanzado",
        "focus": "Integrar los casos AWS existentes en una ruta de producción con seguridad, costo, evidencia y destrucción.",
        "model": "AWS se aprende como una progresión operativa: identidad federada, infraestructura declarativa, entrega, señales, recuperación y costo controlado.",
        "books": ["AWS Well-Architected Framework — AWS", "AWS Cookbook — Culkin y Zazon", "Serverless Architectures on AWS — Peter Sbarski", "Cloud FinOps — Storment y Fuller"],
        "classes": [
            ("Hosting progresivo con Amplify, S3 y CloudFront", "delivery", "aws-static-platform"),
            ("OIDC de GitHub y GitLab hacia AWS sin secretos", "iam", "aws-oidc-federation"),
            ("SAM, Lambda, API Gateway y despliegue serverless", "serverless", "aws-serverless-api"),
            ("DynamoDB por patrones de acceso y single-table design", "data", "aws-dynamodb-model"),
            ("Cognito, JWT authorizers, WAF y defensa en profundidad", "security", "aws-identity-edge"),
            ("EventBridge, SQS, DLQ, replay e idempotencia", "messaging", "aws-event-platform"),
            ("CloudWatch, X-Ray y observabilidad como código", "observability", "aws-observability"),
            ("ECR, ECS Fargate, ALB y autoscaling", "container", "aws-ecs-platform"),
            ("EKS, IRSA, GitOps y operación de clúster", "kubernetes", "aws-eks-gitops"),
            ("Budgets, Cost Explorer, etiquetado y FinOps automatizado", "finops", "aws-cost-control"),
            ("Multi-región, Route 53, failover y game day", "reliability", "aws-dr-drill"),
            ("Proyecto: CloudShop productivo en AWS", "capstone", "cloudshop-aws"),
        ],
    },
    {
        "slug": "azure-production-architecture",
        "title": "Azure: arquitectura empresarial y operación en producción",
        "level": "avanzado",
        "focus": "Operar CloudShop sobre landing zones, PaaS, datos, identidad y observabilidad de Azure.",
        "model": "La arquitectura Azure nace del tenant y las políticas heredables, y llega al workload mediante identidades administradas y redes privadas.",
        "books": ["Azure Architecture Center — Microsoft", "Exam Ref AZ-305 — Microsoft Press", "Designing Distributed Systems — Brendan Burns"],
        "classes": [
            ("Enterprise-scale landing zones y management groups", "governance", "azure-landing-zone"),
            ("Entra ID, workload identity, PIM y Conditional Access", "iam", "azure-identity"),
            ("Hub-spoke, Virtual WAN, Private Link y DNS privado", "network", "azure-network"),
            ("Bicep, deployment stacks y Azure Verified Modules", "iac", "azure-bicep-stack"),
            ("App Service, Functions y Container Apps en producción", "serverless", "azure-app-platform"),
            ("AKS, workload identity, ingress y GitOps", "kubernetes", "azure-aks-platform"),
            ("Azure SQL, Cosmos DB y consistencia distribuida", "data", "azure-data-platform"),
            ("Service Bus, Event Grid y Event Hubs", "messaging", "azure-event-platform"),
            ("Azure Monitor, Application Insights y OpenTelemetry", "observability", "azure-observability"),
            ("Defender for Cloud, Policy y Sentinel", "security", "azure-security-operations"),
            ("Cost Management, Advisor, resiliencia y Chaos Studio", "finops", "azure-optimization"),
            ("Proyecto: CloudShop productivo en Azure", "capstone", "cloudshop-azure"),
        ],
    },
    {
        "slug": "gcp-production-architecture",
        "title": "Google Cloud: arquitectura de datos y operación en producción",
        "level": "avanzado",
        "focus": "Operar CloudShop con la red global, servicios administrados, seguridad y plataforma de datos de Google Cloud.",
        "model": "Google Cloud combina una jerarquía estricta de recursos con una red global y servicios data-first; proyecto, cuota e IAM forman una unidad operativa.",
        "books": ["Google Cloud Architecture Framework — Google", "Google Cloud Certified Professional Cloud Architect Study Guide — Dan Sullivan", "Data Engineering with Google Cloud — Adi Wijaya"],
        "classes": [
            ("Resource Manager, folders, Shared VPC y guardrails", "governance", "gcp-foundation"),
            ("Workload Identity Federation, IAM Conditions y PAM", "iam", "gcp-identity"),
            ("Red global, load balancing, PSC y Cloud DNS", "network", "gcp-network"),
            ("Terraform, Infrastructure Manager y policy validation", "iac", "gcp-iac-stack"),
            ("Cloud Run, Functions, API Gateway y Workflows", "serverless", "gcp-serverless"),
            ("GKE Autopilot, Workload Identity y Config Sync", "kubernetes", "gcp-gke-platform"),
            ("Cloud SQL, Spanner, Firestore y Bigtable", "data", "gcp-operational-data"),
            ("BigQuery, Dataflow, Dataproc y gobernanza de datos", "data", "gcp-analytics-platform"),
            ("Pub/Sub, Eventarc y entrega exactamente-una-vez", "messaging", "gcp-event-platform"),
            ("Cloud Operations, Trace y OpenTelemetry", "observability", "gcp-observability"),
            ("SCC, VPC Service Controls, KMS y FinOps", "security", "gcp-security-finops"),
            ("Proyecto: CloudShop productivo en Google Cloud", "capstone", "cloudshop-gcp"),
        ],
    },
    {
        "slug": "cloud-data-ai-platforms",
        "title": "Plataformas cloud de datos, analítica, IA y agentes",
        "level": "avanzado",
        "focus": "Diseñar plataformas gobernadas para batch, streaming, ML, IA generativa y agentes.",
        "model": "Una plataforma de IA sigue siendo un sistema de datos: necesita procedencia, evaluación, límites de costo, seguridad y operación antes de una interfaz inteligente.",
        "books": ["Designing Machine Learning Systems — Chip Huyen", "Fundamentals of Data Engineering — Reis y Housley", "Building Machine Learning Powered Applications — Emmanuel Ameisen"],
        "classes": [
            ("Lakehouse, warehouse, mesh y contratos de datos", "data", "data-architecture"),
            ("Ingesta batch, CDC y streaming", "data", "ingestion-pipeline"),
            ("Orquestación, calidad, lineage y observabilidad de datos", "observability", "data-reliability"),
            ("Feature stores, training pipelines y experiment tracking", "platform", "ml-platform"),
            ("Serving online, batch inference y escalado de modelos", "performance", "model-serving"),
            ("MLOps, registro, promoción, drift y rollback", "delivery", "mlops-pipeline"),
            ("Modelos fundacionales, tokens, embeddings y RAG", "architecture", "rag-system"),
            ("Bedrock, Azure AI Foundry y Vertex AI", "decision", "genai-provider-adr"),
            ("Agentes, tools, memoria, permisos y guardrails", "security", "agent-architecture"),
            ("Evaluación de IA, red teaming y observabilidad", "testing", "ai-evaluation"),
            ("Privacidad, gobernanza, sostenibilidad y costo de IA", "governance", "responsible-ai-controls"),
            ("Proyecto: asistente operativo de CloudShop", "capstone", "cloudshop-ai-assistant"),
        ],
    },
    {
        "slug": "cloud-operations-automation",
        "title": "Operación cloud, automatización y respuesta a incidentes",
        "level": "avanzado",
        "focus": "Convertir la operación diaria en procesos observables, repetibles y progresivamente automatizados.",
        "model": "Operar es controlar cambios bajo incertidumbre: inventario, señal, diagnóstico, acción reversible y aprendizaje deben formar un ciclo cerrado.",
        "books": ["The Site Reliability Workbook — Beyer et al.", "Seeking SRE — Murphy et al.", "Effective DevOps — Davis y Daniels"],
        "classes": [
            ("Inventario, etiquetado, CMDB y ownership", "governance", "cloud-inventory"),
            ("Patching, imágenes doradas y gestión de configuración", "operations", "patch-strategy"),
            ("Backups, restore testing, vaults e inmutabilidad", "reliability", "backup-restore"),
            ("Administración remota sin SSH permanente", "security", "secure-operations"),
            ("Alertas, on-call, escalamiento y comunicación", "incident", "oncall-system"),
            ("Triage de red, cómputo, datos y dependencias", "incident", "diagnostic-tree"),
            ("Runbooks ejecutables y auto-remediation", "operations", "executable-runbook"),
            ("Change management, ventanas y rollback", "delivery", "change-plan"),
            ("Game days, chaos engineering y aprendizaje", "chaos", "gameday-report"),
            ("Capacity planning, cuotas y gestión de demanda", "capacity", "capacity-plan"),
            ("AIOps, automatización asistida y límites humanos", "governance", "aiops-control"),
            ("Proyecto: centro de operaciones de CloudShop", "capstone", "cloudshop-operations"),
        ],
    },
    {
        "slug": "specializations-certifications-career",
        "title": "Especializaciones, certificaciones y práctica profesional",
        "level": "intermedio-avanzado",
        "focus": "Transformar el conocimiento transversal en perfiles demostrables, preparación certificable y comunicación profesional.",
        "model": "Una especialización combina fundamentos, evidencia de proyectos y juicio bajo restricciones; una insignia sin práctica no sustituye esa combinación.",
        "books": ["The Staff Engineer's Path — Tanya Reilly", "The Manager's Path — Camille Fournier", "Staff Engineer — Will Larson"],
        "classes": [
            ("Ruta Cloud Engineer y mapa de competencias", "decision", "cloud-engineer-plan"),
            ("Ruta DevOps y Delivery Engineer", "decision", "devops-plan"),
            ("Ruta Platform Engineer", "decision", "platform-engineer-plan"),
            ("Ruta Site Reliability Engineer", "decision", "sre-plan"),
            ("Ruta Cloud Security Engineer", "decision", "security-engineer-plan"),
            ("Ruta FinOps Practitioner", "decision", "finops-plan"),
            ("Ruta Cloud Data y AI Engineer", "decision", "data-ai-plan"),
            ("Ruta Cloud Solutions Architect", "decision", "architect-plan"),
            ("Mapeo AWS, Azure, Google Cloud, Kubernetes y FinOps", "assessment", "certification-map"),
            ("Preguntas de escenario y estrategia de examen", "assessment", "exam-simulation"),
            ("Portafolio, evidencia, README y entrevista de sistemas", "assessment", "professional-portfolio"),
            ("Proyecto: defensa técnica ante panel", "capstone", "technical-defense"),
        ],
    },
    {
        "slug": "industry-capstones",
        "title": "Capstones por industria y defensa final",
        "level": "experto",
        "focus": "Integrar arquitectura, implementación, operación, costo y comunicación en casos industriales completos.",
        "model": "El capstone no premia cantidad de servicios, sino trazabilidad entre contexto, decisiones, implementación, fallos, evidencia y aprendizaje.",
        "books": ["Building Evolutionary Architectures — Ford, Parsons y Kua", "Release It! — Michael Nygard", "Accelerate — Forsgren, Humble y Kim"],
        "classes": [
            ("Capstone retail: comercio multi-región", "capstone", "retail-capstone"),
            ("Capstone financiero: pagos, auditoría y recuperación", "capstone", "finance-capstone"),
            ("Capstone salud: privacidad e interoperabilidad", "capstone", "health-capstone"),
            ("Capstone sector público: soberanía y continuidad", "capstone", "public-sector-capstone"),
            ("Capstone media: streaming y distribución global", "capstone", "media-capstone"),
            ("Capstone industria: IoT, edge y operación desconectada", "capstone", "industry-capstone"),
            ("Capstone SaaS: multi-tenancy y unit economics", "capstone", "saas-capstone"),
            ("Capstone datos e IA: plataforma gobernada", "capstone", "data-ai-capstone"),
            ("Game day integrado y respuesta a incidentes", "chaos", "final-gameday"),
            ("Revisión Well-Architected multi-proveedor", "architecture", "final-architecture-review"),
            ("Paquete de evidencia, costos y riesgos residuales", "assessment", "final-evidence-pack"),
            ("Defensa final, retrospectiva y plan de 12 meses", "capstone", "final-defense"),
        ],
    },
]
