"""Canonical curriculum data for the Multi-Cloud Engineering Program."""

PARTS = [
    {
        "slug": "foundations-computing-networking-linux",
        "title": "Fundamentos de computación, redes y Linux",
        "level": "inicial",
        "focus": "Construir el vocabulario y las destrezas técnicas que la nube da por supuestas.",
        "model": "Antes de alquilar infraestructura remota, aprende a observar una computadora local como un conjunto de procesos, redes, archivos, identidades y recursos medibles.",
        "books": ["How Linux Works — Brian Ward", "Computer Networking: A Top-Down Approach — Kurose y Ross", "Pro Git — Chacon y Straub"],
        "classes": [
            ("Computación digital y modelo mental de la nube", "foundation", "mapa-de-componentes"),
            ("Terminal, sistema de archivos, procesos y variables de entorno", "shell", "bitacora-de-comandos"),
            ("Git, GitHub y trabajo reproducible", "git", "repositorio-reproducible"),
            ("Python, JSON y automatización mínima", "automation", "script-de-diagnostico"),
            ("Redes por capas, TCP/IP, puertos y sockets", "network", "captura-y-mapa-de-red"),
            ("DNS, HTTP, HTTPS y TLS de extremo a extremo", "network", "traza-de-solicitud"),
            ("Linux: usuarios, permisos, servicios y logs", "linux", "servicio-auditado"),
            ("Virtualización, hipervisores e imágenes", "virtualization", "comparativa-de-aislamiento"),
            ("APIs REST, autenticación y contratos", "api", "cliente-api-verificado"),
            ("Responsabilidad compartida y pensamiento de riesgo", "security", "matriz-de-responsabilidad"),
            ("Costo, energía, capacidad y medición básica", "finops", "estimacion-de-costo"),
            ("Proyecto: servicio local reproducible y observable", "capstone", "servicio-local"),
        ],
    },
    {
        "slug": "cloud-principles-strategy-adoption",
        "title": "Principios, estrategia y adopción cloud",
        "level": "inicial-intermedio",
        "focus": "Decidir cuándo, por qué y cómo adoptar nube con criterios técnicos y económicos.",
        "model": "La nube es un modelo operativo de acceso bajo demanda, no un lugar mágico ni el centro de datos de otra persona.",
        "books": ["Cloud Strategy — Gregor Hohpe", "Cloud FinOps — Storment y Fuller", "Accelerate — Forsgren, Humble y Kim"],
        "classes": [
            ("Definición NIST y características esenciales de cloud", "foundation", "matriz-nist"),
            ("Regiones, zonas de disponibilidad, puntos de presencia y edge", "architecture", "mapa-de-topologia"),
            ("IaaS, PaaS, SaaS, CaaS y FaaS", "decision", "matriz-de-servicios"),
            ("Elasticidad, escalabilidad, disponibilidad y resiliencia", "reliability", "modelo-de-capacidad"),
            ("Tenancy, cuentas, suscripciones, proyectos y jerarquías", "governance", "arbol-de-recursos"),
            ("Identidad, roles, políticas y federación", "iam", "matriz-rbac"),
            ("Modelo de responsabilidad compartida por servicio", "security", "raci-de-controles"),
            ("TCO, costos variables, unit economics y FinOps", "finops", "caso-tco"),
            ("Well-Architected y atributos de calidad", "architecture", "revision-well-architected"),
            ("Cloud Adoption Framework y modelo operativo", "governance", "backlog-de-adopcion"),
            ("Descubrimiento y clasificación de workloads", "migration", "inventario-de-workloads"),
            ("Proyecto: decisión de migración sustentada con ADR", "capstone", "adr-de-migracion"),
        ],
    },
    {
        "slug": "aws-core-platform",
        "title": "AWS: plataforma esencial",
        "level": "intermedio",
        "focus": "Diseñar y operar una carga completa en AWS con controles explícitos.",
        "model": "Una cuenta AWS es una frontera de seguridad y facturación; los servicios se combinan mediante contratos, no como una lista de productos aislados.",
        "books": ["AWS Well-Architected Framework — AWS", "AWS Cookbook — John Culkin y Mike Zazon", "Amazon Web Services in Action — Wittig y Wittig"],
        "classes": [
            ("Organizations, cuentas, OU, SCP y landing zone", "governance", "landing-zone-aws"),
            ("IAM, roles, políticas, STS y federación", "iam", "politica-iam-aws"),
            ("VPC, subredes, rutas, NAT, endpoints y seguridad", "network", "vpc-aws"),
            ("EC2, AMI, EBS y selección de capacidad", "compute", "instancia-aws"),
            ("Elastic Load Balancing y Auto Scaling", "reliability", "servicio-elastico-aws"),
            ("S3: objetos, versionado, lifecycle y replicación", "storage", "bucket-gobernado-aws"),
            ("RDS, DynamoDB y ElastiCache: decisión de datos", "data", "matriz-datos-aws"),
            ("Lambda, API Gateway y Step Functions", "serverless", "api-serverless-aws"),
            ("SQS, SNS y EventBridge", "messaging", "flujo-eventos-aws"),
            ("CloudWatch, CloudTrail, Config y Systems Manager", "observability", "evidencia-operativa-aws"),
            ("KMS, Secrets Manager, WAF y controles de seguridad", "security", "controles-aws"),
            ("Proyecto: aplicación de tres capas en AWS", "capstone", "plataforma-aws"),
        ],
    },
    {
        "slug": "azure-core-platform",
        "title": "Azure: plataforma esencial",
        "level": "intermedio",
        "focus": "Diseñar y operar una carga empresarial en Azure desde su jerarquía de gobierno.",
        "model": "En Azure, identidad y jerarquía organizacional preceden al recurso: tenant, management group, suscripción y resource group determinan el alcance de control.",
        "books": ["Azure Architecture Center — Microsoft", "Azure for Architects — Ritesh Modi", "Exam Ref AZ-305 — Microsoft Press"],
        "classes": [
            ("Tenant, management groups, suscripciones y resource groups", "governance", "jerarquia-azure"),
            ("Microsoft Entra ID, RBAC, managed identities y PIM", "iam", "identidad-azure"),
            ("Virtual Network, subredes, NSG, UDR, peering y Private Link", "network", "vnet-azure"),
            ("Virtual Machines, Scale Sets y Load Balancer", "compute", "servicio-elastico-azure"),
            ("Blob Storage, Files, redundancia y lifecycle", "storage", "storage-gobernado-azure"),
            ("Azure SQL, Cosmos DB y Azure Cache for Redis", "data", "matriz-datos-azure"),
            ("App Service, Functions y Container Apps", "serverless", "api-plataforma-azure"),
            ("Service Bus, Event Grid y Event Hubs", "messaging", "flujo-eventos-azure"),
            ("Azure Monitor, Log Analytics y Application Insights", "observability", "evidencia-operativa-azure"),
            ("Key Vault, Defender for Cloud y Azure Policy", "security", "controles-azure"),
            ("Bicep, plantillas y despliegues por alcance", "iac", "infraestructura-bicep"),
            ("Proyecto: aplicación de tres capas en Azure", "capstone", "plataforma-azure"),
        ],
    },
    {
        "slug": "gcp-core-platform",
        "title": "Google Cloud: plataforma esencial",
        "level": "intermedio",
        "focus": "Diseñar y operar una carga en Google Cloud con proyectos, identidades y datos bien delimitados.",
        "model": "Un proyecto de Google Cloud es la unidad práctica de API, cuota, IAM y facturación; la organización aporta la política heredable.",
        "books": ["Google Cloud Architecture Framework — Google", "Official Google Cloud Certified Professional Cloud Architect Study Guide — Dan Sullivan", "Data Engineering with Google Cloud Platform — Adi Wijaya"],
        "classes": [
            ("Organización, folders, proyectos, billing y cuotas", "governance", "jerarquia-gcp"),
            ("IAM, service accounts y Workload Identity Federation", "iam", "identidad-gcp"),
            ("VPC global, subredes regionales, firewall y Cloud NAT", "network", "vpc-gcp"),
            ("Compute Engine, managed instance groups y load balancing", "compute", "servicio-elastico-gcp"),
            ("Cloud Storage, clases, lifecycle y replicación", "storage", "bucket-gobernado-gcp"),
            ("Cloud SQL, Spanner, Firestore y Memorystore", "data", "matriz-datos-gcp"),
            ("Cloud Run, Cloud Functions y API Gateway", "serverless", "api-serverless-gcp"),
            ("Pub/Sub, Cloud Tasks y Workflows", "messaging", "flujo-eventos-gcp"),
            ("Cloud Logging, Monitoring, Trace y Audit Logs", "observability", "evidencia-operativa-gcp"),
            ("Cloud KMS, Secret Manager y Security Command Center", "security", "controles-gcp"),
            ("Terraform y despliegues reproducibles en GCP", "iac", "infraestructura-gcp"),
            ("Proyecto: aplicación de tres capas en Google Cloud", "capstone", "plataforma-gcp"),
        ],
    },
    {
        "slug": "containers-docker-oci",
        "title": "Contenedores, Docker y OCI",
        "level": "intermedio",
        "focus": "Empaquetar servicios portables, observables y endurecidos.",
        "model": "Una imagen es un artefacto inmutable; un contenedor es un proceso aislado con límites y dependencias explícitas, no una máquina virtual pequeña.",
        "books": ["Docker Deep Dive — Nigel Poulton", "Container Security — Liz Rice", "Cloud Native Patterns — Cornelia Davis"],
        "classes": [
            ("Imágenes, capas, registros y estándar OCI", "container", "inspeccion-imagen"),
            ("Dockerfile reproducible y builds multi-stage", "container", "imagen-minima"),
            ("Namespaces, cgroups y runtime de contenedores", "container", "mapa-aislamiento"),
            ("Volúmenes, bind mounts y persistencia", "storage", "persistencia-contenedor"),
            ("Redes bridge, DNS interno y publicación de puertos", "network", "red-contenedores"),
            ("Docker Compose y aplicaciones multiservicio", "orchestration", "stack-compose"),
            ("Registros, SBOM, firma y procedencia de imágenes", "supply-chain", "cadena-suministro-imagen"),
            ("Límites, health checks y apagado ordenado", "reliability", "contenedor-operable"),
            ("Rootless, capabilities, seccomp y secretos", "security", "contenedor-endurecido"),
            ("Diagnóstico de CPU, memoria, red y filesystem", "observability", "informe-diagnostico"),
            ("Migración de una aplicación legacy a contenedores", "migration", "plan-modernizacion"),
            ("Proyecto: stack OCI endurecido y observable", "capstone", "plataforma-contenedores"),
        ],
    },
    {
        "slug": "kubernetes-managed-platforms",
        "title": "Kubernetes y plataformas administradas",
        "level": "intermedio-avanzado",
        "focus": "Operar cargas declarativas y portables sobre EKS, AKS o GKE.",
        "model": "Kubernetes es un sistema de reconciliación: declaras estado deseado y controladores reducen continuamente la diferencia con el estado observado.",
        "books": ["Kubernetes: Up and Running — Burns, Beda y Hightower", "Kubernetes Patterns — Ibryam y Huß", "Production Kubernetes — Rosso et al."],
        "classes": [
            ("API server, etcd, scheduler, controllers y kubelet", "kubernetes", "mapa-control-plane"),
            ("Pods, ReplicaSets, Deployments y Jobs", "kubernetes", "workload-kubernetes"),
            ("Services, DNS, Ingress y Gateway API", "network", "exposicion-kubernetes"),
            ("ConfigMaps, Secrets y configuración externa", "configuration", "configuracion-kubernetes"),
            ("Volumes, PersistentVolumes, CSI y StatefulSets", "storage", "estado-kubernetes"),
            ("Requests, limits, scheduling y autoscaling", "capacity", "capacidad-kubernetes"),
            ("Probes, rollouts, rollback y PodDisruptionBudget", "reliability", "despliegue-resiliente"),
            ("Namespaces, RBAC, NetworkPolicy y admission", "security", "tenant-kubernetes"),
            ("Helm, Kustomize y gestión de paquetes", "configuration", "paquete-kubernetes"),
            ("Logs, métricas, eventos y depuración", "observability", "diagnostico-kubernetes"),
            ("EKS, AKS y GKE: similitudes y diferencias", "decision", "matriz-kubernetes-administrado"),
            ("Proyecto: plataforma Kubernetes portable", "capstone", "plataforma-kubernetes"),
        ],
    },
    {
        "slug": "infrastructure-as-code-configuration",
        "title": "Infraestructura como código y configuración",
        "level": "intermedio-avanzado",
        "focus": "Convertir infraestructura y políticas en cambios revisables, probables y repetibles.",
        "model": "IaC trata la infraestructura como producto versionado: el plan explica intención, el estado conecta intención y realidad, y la revisión reduce cambios accidentales.",
        "books": ["Infrastructure as Code — Kief Morris", "Terraform: Up & Running — Yevgeniy Brikman", "Ansible for DevOps — Jeff Geerling"],
        "classes": [
            ("Declarativo, imperativo, idempotencia y convergencia", "iac", "comparativa-iac"),
            ("Terraform: HCL, providers, resources y grafo", "iac", "stack-terraform"),
            ("Estado remoto, locking, cifrado y recuperación", "iac", "backend-terraform"),
            ("Módulos, contratos, versiones y composición", "iac", "modulo-terraform"),
            ("Variables, outputs, locals y data sources", "iac", "interfaz-infraestructura"),
            ("Plan, apply, drift, import y refactor con moved", "iac", "ciclo-cambio-iac"),
            ("Validación, lint, pruebas y policy as code", "testing", "pipeline-iac"),
            ("Secretos y datos sensibles en IaC", "security", "modelo-secretos-iac"),
            ("CloudFormation, Bicep, Pulumi y Terraform", "decision", "adr-herramienta-iac"),
            ("Ansible e imagen dorada para configuración", "configuration", "configuracion-servidor"),
            ("Plantillas, golden paths y catálogo interno", "platform", "plantilla-plataforma"),
            ("Proyecto: infraestructura multiambiente promovible", "capstone", "plataforma-iac"),
        ],
    },
    {
        "slug": "continuous-delivery-platform-engineering",
        "title": "Entrega continua y platform engineering",
        "level": "avanzado",
        "focus": "Diseñar un flujo de entrega rápido, seguro y observable para equipos de producto.",
        "model": "Una plataforma interna ofrece capacidades como productos y reduce carga cognitiva mediante caminos dorados, sin quitar autonomía donde importa.",
        "books": ["Continuous Delivery — Humble y Farley", "Accelerate — Forsgren, Humble y Kim", "Team Topologies — Skelton y Pais"],
        "classes": [
            ("Integración continua, trunk-based development y feedback", "delivery", "flujo-ci"),
            ("GitHub Actions: workflows, runners, permisos y caché", "delivery", "pipeline-github-actions"),
            ("Artefactos inmutables, semver y promoción", "supply-chain", "registro-artefactos"),
            ("Pruebas, calidad y puertas de cambio", "testing", "quality-gates"),
            ("SAST, SCA, secretos, SBOM y firma en pipeline", "security", "pipeline-devsecops"),
            ("Rolling, blue-green, canary y rollback", "delivery", "estrategia-despliegue"),
            ("GitOps con Argo CD o Flux", "gitops", "reconciliacion-gitops"),
            ("Ambientes efímeros y promoción entre entornos", "delivery", "flujo-ambientes"),
            ("Feature flags y separación deploy-release", "delivery", "plan-feature-flags"),
            ("Platform engineering e Internal Developer Platform", "platform", "mapa-capacidades-plataforma"),
            ("Developer experience, DORA y carga cognitiva", "metrics", "tablero-dora"),
            ("Proyecto: fábrica de software multi-cloud", "capstone", "plataforma-entrega"),
        ],
    },
    {
        "slug": "data-messaging-serverless-integration",
        "title": "Datos, mensajería, serverless e integración",
        "level": "avanzado",
        "focus": "Elegir servicios de datos e integración por sus garantías y patrones de acceso.",
        "model": "La base de datos correcta depende del patrón de acceso y de las garantías necesarias; distribuir datos convierte latencia, consistencia y fallos parciales en decisiones de diseño.",
        "books": ["Designing Data-Intensive Applications — Martin Kleppmann", "Enterprise Integration Patterns — Hohpe y Woolf", "Building Event-Driven Microservices — Adam Bellemare"],
        "classes": [
            ("Bases relacionales administradas y pooling", "data", "modelo-relacional"),
            ("NoSQL: clave-valor, documento, columna y grafo", "data", "matriz-nosql"),
            ("Caché, invalidación, TTL y consistencia", "data", "estrategia-cache"),
            ("Object storage, data lake y formatos columnares", "data", "diseno-data-lake"),
            ("Colas, entrega, reintentos y dead-letter queues", "messaging", "cola-resiliente"),
            ("Pub/sub, streams, particiones y orden", "messaging", "stream-particionado"),
            ("Arquitectura dirigida por eventos y contratos", "architecture", "catalogo-eventos"),
            ("Sagas, outbox, idempotencia y deduplicación", "distributed", "transaccion-distribuida"),
            ("Serverless: límites, cold starts y concurrencia", "serverless", "funcion-operable"),
            ("API management, cuotas, versiones y monetización", "api", "producto-api"),
            ("Workflows y orquestación durable", "orchestration", "workflow-durable"),
            ("Proyecto: pipeline de pedidos orientado a eventos", "capstone", "plataforma-eventos"),
        ],
    },
    {
        "slug": "observability-sre-reliability",
        "title": "Observabilidad, SRE y confiabilidad",
        "level": "avanzado",
        "focus": "Operar sistemas mediante señales, objetivos y aprendizaje de incidentes.",
        "model": "La confiabilidad es una característica del servicio percibido por usuarios; SRE la administra con objetivos explícitos y presupuestos de error.",
        "books": ["Site Reliability Engineering — Beyer et al.", "The Site Reliability Workbook — Beyer et al.", "Observability Engineering — Majors, Fong-Jones y Miranda"],
        "classes": [
            ("Logs, métricas, trazas y eventos como señales", "observability", "mapa-telemetria"),
            ("Logging estructurado, correlación y retención", "observability", "contrato-logs"),
            ("Métricas, cardinalidad y modelos RED y USE", "metrics", "catalogo-metricas"),
            ("Tracing distribuido y OpenTelemetry", "observability", "traza-distribuida"),
            ("Dashboards, alertas accionables y fatiga", "observability", "tablero-operativo"),
            ("SLI, SLO, SLA y presupuesto de error", "sre", "slo-servicio"),
            ("Incidentes, severidad, comando y comunicación", "incident", "plan-incidente"),
            ("Runbooks, playbooks y automatización operativa", "operations", "runbook-verificado"),
            ("Capacidad, rendimiento y pruebas de carga", "performance", "informe-carga"),
            ("Timeouts, retries, backoff, circuit breaker y bulkhead", "reliability", "cliente-resiliente"),
            ("Chaos engineering y game days", "chaos", "experimento-caos"),
            ("Proyecto: operación SRE de CloudShop", "capstone", "plataforma-sre"),
        ],
    },
    {
        "slug": "security-governance-finops",
        "title": "Seguridad, gobierno, cumplimiento y FinOps",
        "level": "avanzado",
        "focus": "Construir guardrails que hagan segura y económicamente sostenible la autonomía.",
        "model": "Gobernar no significa aprobar cada cambio: significa codificar límites, evidencia y responsabilidades para que los equipos puedan avanzar con seguridad.",
        "books": ["Practical Cloud Security — Chris Dotson", "Cloud Security Handbook — Eyal Estrin", "Cloud FinOps — Storment y Fuller"],
        "classes": [
            ("Zero Trust y defensa en profundidad", "security", "modelo-zero-trust"),
            ("Mínimo privilegio, acceso temporal y separación de funciones", "iam", "revision-accesos"),
            ("Segmentación, perímetro, WAF, DDoS y egress", "network", "arquitectura-defensiva"),
            ("Cifrado, KMS, HSM, rotación y envelope encryption", "security", "jerarquia-claves"),
            ("Gestión de secretos y credenciales de workloads", "security", "ciclo-secretos"),
            ("Vulnerabilidades, imágenes y cadena de suministro", "supply-chain", "informe-supply-chain"),
            ("CSPM, postura, policy as code y remediación", "governance", "guardrail-policy"),
            ("Threat modeling con STRIDE y attack paths", "security", "modelo-amenazas"),
            ("Cumplimiento, residencia, privacidad y evidencia", "compliance", "matriz-controles"),
            ("FinOps: showback, chargeback, budgets y anomalías", "finops", "modelo-asignacion-costos"),
            ("Optimización de costo, capacidad y sostenibilidad", "finops", "backlog-optimizacion"),
            ("Proyecto: landing zone con guardrails", "capstone", "landing-zone-gobernada"),
        ],
    },
    {
        "slug": "cloud-native-distributed-architecture",
        "title": "Arquitectura cloud-native y sistemas distribuidos",
        "level": "avanzado-experto",
        "focus": "Tomar decisiones de arquitectura con compensaciones explícitas y evidencia.",
        "model": "Una arquitectura es un conjunto de decisiones costosas de cambiar; su calidad se juzga contra escenarios concretos, no por la cantidad de servicios usados.",
        "books": ["Cloud Native Patterns — Cornelia Davis", "Building Microservices — Sam Newman", "Release It! — Michael Nygard", "Designing Data-Intensive Applications — Martin Kleppmann"],
        "classes": [
            ("Requisitos, restricciones y atributos de calidad", "architecture", "quality-attribute-scenarios"),
            ("Twelve-Factor App y configuración cloud-native", "architecture", "revision-twelve-factor"),
            ("DDD, bounded contexts y ownership de datos", "architecture", "context-map"),
            ("Monolito modular, microservicios y función", "decision", "adr-descomposicion"),
            ("CAP, PACELC y consistencia por operación", "distributed", "matriz-consistencia"),
            ("Replicación, particionado y consenso", "distributed", "modelo-replicacion"),
            ("Fallos parciales y patrones de resiliencia", "reliability", "mapa-fallos"),
            ("Service discovery, malla y comunicación", "network", "topologia-servicios"),
            ("Contratos API, compatibilidad y evolución", "api", "contrato-versionado"),
            ("Multi-tenancy, aislamiento y noisy neighbor", "architecture", "modelo-tenancy"),
            ("Rendimiento, costo, seguridad y operabilidad", "decision", "tradeoff-analysis"),
            ("Proyecto: revisión de arquitectura con ADR", "capstone", "architecture-review"),
        ],
    },
    {
        "slug": "multicloud-hybrid-disaster-recovery",
        "title": "Multi-cloud, híbrido, migración y recuperación",
        "level": "experto",
        "focus": "Diseñar continuidad y portabilidad sin ocultar complejidad, latencia ni egress.",
        "model": "Multi-cloud es una decisión de negocio y riesgo; duplicar cada componente entre proveedores rara vez es la forma más confiable o económica de lograrla.",
        "books": ["Cloud Strategy — Gregor Hohpe", "Seeking SRE — Blank-Edelman", "Enterprise Integration Patterns — Hohpe y Woolf"],
        "classes": [
            ("Motivaciones y anti-patrones de multi-cloud", "decision", "decision-multicloud"),
            ("Portabilidad, capas de abstracción y lock-in", "architecture", "matriz-portabilidad"),
            ("Federación de identidad entre nubes", "iam", "federacion-multicloud"),
            ("Conectividad, tránsito, DNS y service discovery", "network", "red-multicloud"),
            ("Replicación de datos, soberanía y costos de egress", "data", "estrategia-datos-multicloud"),
            ("Observabilidad y operación entre proveedores", "observability", "telemetria-multicloud"),
            ("Terraform multi-provider y separación de estados", "iac", "iac-multicloud"),
            ("Flotas Kubernetes y políticas comunes", "kubernetes", "fleet-kubernetes"),
            ("Nube híbrida, edge y conectividad privada", "hybrid", "arquitectura-hibrida"),
            ("Backup, RTO, RPO y patrones de disaster recovery", "reliability", "plan-dr"),
            ("Las 7R de migración y oleadas", "migration", "roadmap-migracion"),
            ("Proyecto: continuidad activa-pasiva entre nubes", "capstone", "plataforma-multicloud"),
        ],
    },
    {
        "slug": "advanced-platform-capstones-career",
        "title": "Plataformas avanzadas, capstones y carrera",
        "level": "experto-frontera",
        "focus": "Integrar tecnología, operación, gobierno y comunicación en evidencia profesional.",
        "model": "El nivel experto no consiste en conocer más productos, sino en formular mejores preguntas, validar supuestos y sostener decisiones frente a costo, riesgo y operación.",
        "books": ["Team Topologies — Skelton y Pais", "Accelerate — Forsgren, Humble y Kim", "Fundamentals of Software Architecture — Richards y Ford"],
        "classes": [
            ("Landing zones empresariales y vending de cuentas", "governance", "landing-zone-empresarial"),
            ("Gobierno federado y policy as code a escala", "governance", "modelo-gobierno"),
            ("Platform as a Product y roadmap de capacidades", "platform", "roadmap-plataforma"),
            ("Modelo operativo FinOps y economía unitaria", "finops", "operating-model-finops"),
            ("Madurez SRE y confiabilidad organizacional", "sre", "assessment-sre"),
            ("Arquitectura de seguridad cloud empresarial", "security", "security-reference-architecture"),
            ("Workloads de IA, GPU, datos y MLOps multi-cloud", "ai", "arquitectura-ia-cloud"),
            ("Edge, IoT y procesamiento desconectado", "edge", "arquitectura-edge"),
            ("Soberanía digital y confidential computing", "security", "decision-soberania"),
            ("Capstone: descubrimiento y diseño", "capstone", "dossier-diseno-final"),
            ("Capstone: implementación y operación", "capstone", "evidencia-implementacion-final"),
            ("Capstone: defensa, portafolio y plan profesional", "capstone", "defensa-final"),
        ],
    },
]


LAB_EXPECTATIONS = {
    "foundation": "un mapa con fronteras, entradas, salidas y supuestos",
    "shell": "una bitácora reproducible de comandos y resultados",
    "git": "un historial pequeño, legible y verificable",
    "automation": "un script idempotente con salida estructurada",
    "network": "una topología con rutas, puertos y controles",
    "linux": "un servicio con identidad, permisos y logs inspeccionados",
    "virtualization": "una comparación medida de aislamiento y consumo",
    "api": "un contrato versionado con pruebas positivas y negativas",
    "security": "un control con amenaza, mitigación y evidencia",
    "finops": "un cálculo trazable con unidad, supuesto y sensibilidad",
    "capstone": "un incremento integrado, demostrable y documentado",
    "architecture": "un diagrama acompañado por decisiones y trade-offs",
    "decision": "una matriz de decisión ponderada y un ADR",
    "reliability": "un escenario de fallo con objetivo y recuperación medida",
    "governance": "una jerarquía de política, ownership y evidencia",
    "iam": "una matriz de acceso mínimo con prueba de denegación",
    "migration": "un inventario, dependencias, riesgo y oleadas",
    "compute": "una selección de capacidad justificada y observable",
    "storage": "una política de durabilidad, acceso, retención y costo",
    "data": "un modelo de datos ligado a patrones de acceso",
    "serverless": "una función con límites, reintentos e idempotencia",
    "messaging": "un flujo que declara orden, entrega y manejo de errores",
    "observability": "telemetría correlacionada con una pregunta operativa",
    "iac": "un plan reproducible sin secretos ni cambios inesperados",
    "container": "una imagen mínima, escaneada y ejecutada sin privilegios",
    "orchestration": "servicios coordinados con health checks y apagado limpio",
    "supply-chain": "procedencia, inventario y verificación del artefacto",
    "kubernetes": "manifiestos declarativos con estado observado",
    "configuration": "configuración separada, validada y promovible",
    "capacity": "requests, límites y una decisión de escalado medida",
    "testing": "pruebas automatizadas con fallos diagnósticos",
    "platform": "una capacidad autoservicio con contrato y golden path",
    "delivery": "un pipeline con gates, promoción y rollback",
    "gitops": "reconciliación declarativa y evidencia de drift",
    "metrics": "métricas definidas, consultables y vinculadas a una decisión",
    "distributed": "una traza de consistencia, reintento o fallo parcial",
    "sre": "un SLO con presupuesto de error y política de acción",
    "incident": "una cronología, roles, comunicación y aprendizaje",
    "operations": "un runbook probado por otra persona",
    "performance": "una prueba de carga con baseline y cuello de botella",
    "chaos": "una hipótesis de resiliencia y criterio de abortar",
    "compliance": "un control mapeado a evidencia y responsable",
    "hybrid": "una topología híbrida con dependencia y modo degradado",
    "ai": "una arquitectura de IA con datos, cómputo, costo y seguridad",
    "edge": "un flujo edge que tolera desconexión y sincroniza estado",
}
